# Generated by Django 4.2.7 on 2023-11-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renamedfile',
            options={'verbose_name': 'Renamed File', 'verbose_name_plural': 'Renamed Files'},
        ),
    ]
